### ISSUE TITLE
Place all clients urls in config file

### ISSUE THREAD

**Issue by musinit** [trustwallet/go-libs#191]
There are a lot of lines with hardcoded URLs like

func (c Client) FetchMarketPairs(limit int) (pairs []MarketPair, err error) {
	params := url.Values{"limit": {strconv.Itoa(limit)}}
	err = c.req.Get(&pairs, "**/api/v1/markets**", params)
	return pairs, err
}

What if we move it out from these methods and place in config file, so it would be easier to track and change it in future

**Comment by CustomerTeam001** [comment]
We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/FhSmn4AznQtZcruX8
